/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-02-16 16:56:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Employee Information</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(" body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            background-position:center;\r\n");
      out.write("            background-image: linear-gradient(\r\n");
      out.write("      115deg,\r\n");
      out.write("      rgba(58, 58, 158, 0.8),\r\n");
      out.write("      rgba(136, 136, 206, 0.7)\r\n");
      out.write("    ),\r\n");
      out.write("    url(https://cdn.freecodecamp.org/testable-projects-fcc/images/survey-form-background.jpeg);\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("  \r\n");
      out.write("        }\r\n");
      out.write(".mar{\r\n");
      out.write("margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("<h1 style=\"color:white;\" align=\"center\">Update Employee Details</h1>\r\n");
      out.write("<table  class=\"mar\">\r\n");
      out.write("\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">Enter the Emp_id:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"empId\" id=\"empId\" placeholder=\"empId\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">First Name:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"firstName\" id=\"firstName\" placeholder=\"firstName\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">Last Name:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"lastName\" id=\"lastName\" placeholder=\"lastName\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">DOB:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"date\" name=\"age\" id=\"age\" placeholder=\"DOB\" ></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">MobileNumber:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"mobileNo\" id=\"mobileNo\" pattern=\"^[0-9]{10}$\" title=\"Please Enter Valid Mobile Number\" placeholder=\"MobileNo\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr><td><label style=\"color:white;\"><h2 style=\"outline: 1px; padding: 0px; margin: 0px;\">Address</h2></label></td></tr>\r\n");
      out.write("\r\n");
      out.write("	<tr><td><label style=\"color:white;\" ><h3 style=\"outline: 1px; padding: 0px; margin: 0px;\">Current Address</h3></label></td></tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">HouseNumber</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"hno\" pattern=\"^[0-9]{1,10}$\" title=\"Please Enter Valid House Number\" id=\"hno\" placeholder=\"Hno\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">City:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"city\" id=\"city\" placeholder=\"City\" maxlength=\"32\" pattern=\"[A-Za-z]{1,32}\" title=\"Please Enter Valid City Name\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">State:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"state\" id=\"state\" placeholder=\"State\" maxlength=\"32\" pattern=\"[A-Za-z]{1,32}\" title=\"Please Enter Valid State Name\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">PinCode:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"pincode\" id=\"pincode\" pattern=\"^[0-9]{6}$\" title=\"Please Enter Valid Pin Code\" placeholder=\"Pincode\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr><td><label style=\"color:white;\"><h3 style=\"outline: 1px; padding: 0px; margin: 0px;\">Permanent Address</h3></label></td></tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">HouseNumber:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"hno1\" id=\"hno1\" pattern=\"^[0-9]{1,10}$\" title=\"Please Enter Valid House Number\" placeholder=\"Hno\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">City:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"city1\" id=\"city1\" maxlength=\"32\" pattern=\"[A-Za-z]{1,32}\" title=\"Please Enter Valid City Name\" placeholder=\"City\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">State:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"state1\" id=\"state1\" maxlength=\"32\" pattern=\"[A-Za-z]{1,32}\" title=\"Please Enter Valid State Name\" placeholder=\"State\" ></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td><label style=\"color:white;\">PinCode:</label></td>\r\n");
      out.write("		<td><input style=\"width: 100%; border: 2px solid red; border-radius:4px;padding:3px 4px;margin:2px 0px;box-sizing: border-box;\" type=\"text\" name=\"pincode1\" id=\"pincode1\" pattern=\"^[0-9]{6}$\" title=\"Please Enter Valid Pin Code\" placeholder=\"Pincode\" ></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<tr>\r\n");
      out.write("	<td>	\r\n");
      out.write("		<input type=\"submit\" style=\"height: 40px; border-radius: 20px; margin-top: 10px; width: 100px;\" value=\"update\"></td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
